//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DPR2UI.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DPR2UITYPE                  130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_STATIONVIEW             134
#define ID_NEW_DIR                      135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_RW_SAVE                      145
#define ID_RW_LOAD                      146
#define ID_RW_TEXT                      147
#define ID_RW_OPEN                      148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_SAVE_PROPERTIES              152
#define ID_PROPERTIES2                  153
#define IDS_FILE_VIEW                   155
#define IDS_STATION_VIEW                156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_FILE                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_COMBOBOX_COMM               185
#define IDR_MFCPROPERTYGRIDCTRL         186
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_WARN_TAB                    300
#define IDS_RETURN_TAB                  301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_POPUP_FAULTFRM              307
#define IDR_POPUP_FAULTFILE             308
#define IDR_POPUP_SETTING               309
#define IDR_POPUP_STATION               310
#define ID_STATION_ADD                  311
#define ID_STATION_DEL                  312
#define ID_STATION_DEL_ALL              313
#define ID_STASION_CONNECT              314
#define ID_STASION_DISCONNECT           315
#define ID_DEV_ADD                      316
#define ID_DEV_DEL                      317
#define ID_DEV_DEL_ALL                  318
#define ID_OPEN_LOCAL_MENU              319
#define ID_STATION_PROPERTY             320
#define ID_FAULTFILE_MENU               321
#define ID_FAULTFILE_SHOWMENU           322
#define ID_FAULTFILE_GET                323
#define ID_FAULTFILE_ANALYSIS           324
#define ID_REFRESH                      326
#define ID_SETTING_VERITY               330
#define ID_SETTING_SHOW                 331
#define ID_SETTING_GET                  332
#define ID_SETTING_PUT                  333
#define ID_SETTING_SAVE                 334
#define ID_SETTING_LOAD                 335
#define ID_SETTING_COPY                 335
#define ID_SETTING_PASTE                336
#define ID_EXPAND_ALL                   337
#define ID_COLLAPSE_ALL                 338
#define ID_OP_TRIGRECORD                339
#define ID_OP_RECVTIME                  340
#define ID_OP_SETTIME                   341
#define IDR_POPUP_SETTINGFRM            349
#define IDR_FAULTFILETYPE               350
#define IDR_SETTINGTYPE                 351
#define IDD_DIALOG_PATCH                352
#define IDR_POPUP_OPERATING             353
#define IDR_POPUP_STATION_DIAL          354
#define ID_STATION_DIAL                 355
#define ID_STATION_HANG                 356
#define IDC_EDIT_END                    1004
#define IDC_EDIT_START                  1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
